#!/bin/bash

if ping -c1 homehost >/dev/null && mount | grep -q "/mnt/homehost/roydsd"; then
   date -d @`expr $(date +%s) / 300 \* 300` '+%H:%M%t--- %A ---%t%t%t%x' >> /mnt/homehost/roydsd/Tait/Hours_and_time-sheets/Time_break-down.txt
fi

