#!/bin/bash

mountdir="/mnt/homehost/roydsd"
time_sheets="$mountdir/Tait/Hours_and_time-sheets"

if ! grep "$mountdir" <(mount) >/dev/null; then
   echo "$mountdir not mounted"
   exit 1
fi

this_year=$(\date +%Y)
year=$(($this_year - 4))
{
   cat $time_sheets/Time_break-down.txt;
   while [ $((year++)) -lt $this_year ]; do
      cat $time_sheets/archive/$year/*
   done
} | analyse_time_break_down | less

