#!/bin/bash

if ! grep "/mnt/homehost/roydsd" <(mount) >/dev/null; then
   echo "//homehost/roydsd not mounted"
   exit 1
fi

cd /mnt/homehost/roydsd/Tait/Hours_and_time-sheets/archive
last_year_time_break_downs=$(ls $(($(\date +%Y) - 1))/* | egrep '^20../..(0[789]|1[012])...txt')
this_year_time_break_downs=$(ls $(\date +%Y)/*          | egrep '^20../..(0[123456])...txt')

cat $last_year_time_break_downs $this_year_time_break_downs | analyse_time_break_down_weighted | less

